# Generated by Django 3.0.8 on 2020-10-25 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('attribute1', models.CharField(max_length=15)),
                ('attribute2', models.CharField(max_length=15)),
                ('attribute3', models.CharField(max_length=15)),
                ('attribute4', models.CharField(max_length=15)),
                ('attribute5', models.CharField(max_length=15)),
                ('archived', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('attribute1', models.CharField(max_length=15)),
                ('attribute2', models.CharField(max_length=15)),
                ('attribute3', models.CharField(max_length=15)),
                ('attribute4', models.CharField(max_length=15)),
                ('attribute5', models.CharField(max_length=15)),
                ('notes', models.TextField(max_length=100)),
                ('image', models.URLField()),
                ('ranking', models.IntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='lists.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
