# Generated by Django 3.0.8 on 2020-10-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('attribute1', models.CharField(blank=True, max_length=15, null=True)),
                ('attribute2', models.CharField(blank=True, max_length=15, null=True)),
                ('attribute3', models.CharField(blank=True, max_length=15, null=True)),
                ('attribute4', models.CharField(blank=True, max_length=15, null=True)),
                ('attribute5', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('attribute1', models.CharField(blank=True, max_length=15, null=True)),
                ('attribute2', models.CharField(blank=True, max_length=15, null=True)),
                ('attribute3', models.CharField(blank=True, max_length=15, null=True)),
                ('attribute4', models.CharField(blank=True, max_length=15, null=True)),
                ('attribute5', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='lists.Collection')),
            ],
        ),
    ]
