# Generated by Django 3.0.8 on 2020-10-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201029_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/20201029/ef82c6c6a50b415690b6bdef276079ed'),
        ),
    ]
