# Generated by Django 3.0.8 on 2020-10-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201025_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ranking',
            field=models.IntegerField(blank=True),
        ),
    ]
