# Generated by Django 3.0.8 on 2021-01-19 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20210119_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='shared_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
