# Generated by Django 3.0.8 on 2020-10-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201029_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
