# Generated by Django 3.0.8 on 2020-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20201104_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
