# Generated by Django 3.0.8 on 2020-11-13 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20201104_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_collections', to='lists.Collection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_items', to='lists.Item')),
            ],
            options={
                'unique_together': {('collection', 'item')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='ranking',
            field=models.ManyToManyField(related_name='items_ranking', through='lists.Ranking', to='lists.Item'),
        ),
    ]
