# Generated by Django 3.0.8 on 2020-11-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20201113_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='ranking',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
